// Backup of old categories structure
export const MAJOR_CATEGORIES_OLD = [
  { emoji: '💰', name: 'Rendimento', subcategories: ['Salario'] },
  {
    emoji: '🎁',
    name: 'Rendimento Extra',
    subcategories: [
      'Vendas Usados',
      'Autocaravana',
      'Prendas',
      'Outros Rendimentos',
      'Projectos',
      'Crédito Habitação',
      'Reembolsos',
    ],
  },
  { emoji: '🏦', name: 'Economia e Investimentos', subcategories: ['Poupança', 'Investimento'] },
  {
    emoji: '🏠',
    name: 'Custos Fixos',
    subcategories: ['Subscrições', 'Alimentação', 'Transportes', 'Casa', 'Axl', 'Conta Conjunta'],
  },
  {
    emoji: '🛒',
    name: 'Custos Variáveis',
    subcategories: [
      'Parentalidade',
      'Cuidados Pessoais',
      'Saúde',
      'Desporto',
      'Desenvolvimento Pessoal',
      'Subscrições',
      'Alimentação',
      'Transportes',
      'Educação',
      'Solidariedade',
      'Casa',
      'Axl',
      'Multa',
      'Comissões',
      'Desconhecido',
      'Trabalho',
      'Lazer',
      'Levantamento',
    ],
  },
  {
    emoji: '🎉',
    name: 'Gastos sem Culpa',
    subcategories: ['Prendas', 'Compras Gerais', 'Lazer', 'Casa'],
  },
  {
    emoji: '🐷',
    name: 'Poupança',
    subcategories: [
      'Fundo de Emergência',
      'Poupança Household',
      'Poupança Pessoal',
      'Emergency Buffer',
    ],
  },
  {
    emoji: '📈',
    name: 'Investimento',
    subcategories: [
      'PPR',
      'Ações / ETF',
      'Criptomoeda',
      'Depósito a Prazo',
      'Arte',
      'TAFI',
      'Herança',
    ],
  },
  {
    emoji: '↔️',
    name: 'Transferências',
    subcategories: ['Mensalidade', 'Entre Contas', 'Monetária'],
  },
] as const
